version: "3.9"
services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OLLAMA_WEBUI_PORT}:8080
    environment:
      - 'OLLAMA_API_BASE_URL=http://127.0.0.1:11434'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
volumes:
  open-webui: {}